
import React from 'react';
import { BrainPillars, GradeLevel, ReadingLens, ComplexityVector } from '../types';

interface BrainAnalyticsProps {
  pillars: BrainPillars;
  brainPower: number;
  maxLevelReached: number;
  sessionFinished: boolean;
}

export const BrainAnalytics: React.FC<BrainAnalyticsProps> = ({ pillars, brainPower, maxLevelReached, sessionFinished }) => {
  const getGrade = (l: number): GradeLevel => Math.min(7, 3 + Math.floor(l/2)) as GradeLevel;

  const errorByLens = pillars.itemLog.reduce((acc, item) => {
    if (!item.isCorrect) {
      acc[item.lens] = (acc[item.lens] || 0) + 1;
    }
    return acc;
  }, {} as Record<ReadingLens, number>);

  const profile: ComplexityVector = pillars.itemLog.reduce((acc, item) => {
    return {
      lex: Math.max(acc.lex, item.complexity.lex),
      syntax: Math.max(acc.syntax, item.complexity.syntax),
      concept: Math.max(acc.concept, item.complexity.concept),
      domain: Math.max(acc.domain, item.complexity.domain),
      discourse: Math.max(acc.discourse, item.complexity.discourse)
    };
  }, { lex: 0, syntax: 0, concept: 0, domain: 0, discourse: 0 });

  const handleExport = () => {
    const date = new Date().toLocaleString();
    const appName = "STAR Reading × Range & Complexity";
    
    let telemetryContent = pillars.itemLog.map((item, index) => `
=== ITEM ${index + 1} ===
Item ID: ${item.id}
Complexity Level: ${item.complexityLevel}
Complexity Vector: L${item.complexity.lex} S${item.complexity.syntax} C${item.complexity.concept} D${item.complexity.domain} Dis${item.complexity.discourse}
Lens: ${item.lens}
Correct Index: ${item.correctIndex}
Chosen Index: ${item.chosenIndex}
Is Correct: ${item.isCorrect}
Time (ms): ${item.timeMs}
Passage: ${item.passage}
Question: ${item.question}
Timestamp: ${item.timestamp}
`).join("\n");

    const text = `
${appName} - RANGE & COMPLEXITY REPORT
--------------------------------------
Date: ${date}

${telemetryContent}

=== SESSION SUMMARY ===
Max Complexity Stage Reached: ${maxLevelReached + 1}
Accuracy: ${Math.round((pillars.totalAnswers / (pillars.attempts || 1)) * 100)}%
Cognitive Load Mastery: ${Math.round(brainPower)}

FIVE-AXIS READING PROFILE (Highest Sustained):
- Lexical: ${profile.lex}
- Syntactic: ${profile.syntax}
- Conceptual: ${profile.concept}
- Domain: ${profile.domain}
- Discourse: ${profile.discourse}

ERRORS BY LENS:
${Object.entries(errorByLens).map(([k, v]) => `- ${k}: ${v}`).join('\n') || "None"}

--------------------------------------
Generated by UnCommon Core Logic Systems
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `aria_star_reading_range_complexity.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      <div className="ucc-card p-10 border-2 border-[#4EABBC]/30 shadow-2xl relative overflow-hidden">
        <div className="flex justify-between items-center mb-10">
          <h2 className="ucc-title text-4xl text-[#111827]">📊 Range & Complexity Report</h2>
          {sessionFinished && (
            <button onClick={handleExport} className="px-6 py-2.5 bg-[#4EABBC] text-white font-black uppercase text-[10px] rounded-xl">
              Export Analysis (.txt)
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Five-Axis Sustainment Profile</h3>
            <div className="space-y-4">
              {[
                { label: 'Lexical', val: profile.lex },
                { label: 'Syntax', val: profile.syntax },
                { label: 'Conceptual', val: profile.concept },
                { label: 'Domain', val: profile.domain },
                { label: 'Discourse', val: profile.discourse }
              ].map(dim => (
                <div key={dim.label} className="space-y-1">
                  <div className="flex justify-between text-sm font-bold">
                    <span>{dim.label}</span>
                    <span>Level {dim.val}</span>
                  </div>
                  <div className="w-full h-2 bg-gray-100 rounded-full overflow-hidden border border-gray-200">
                    <div 
                      className="h-full bg-gradient-to-r from-[#4EABBC] to-[#E9604F] transition-all duration-1000"
                      style={{ width: `${(dim.val / 5) * 100}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex flex-col justify-center items-center p-8 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Reader Sustainment Summary</h3>
            <div className="text-center space-y-4">
               <p className="text-gray-600 font-medium leading-relaxed italic">
                 "This reader sustained complexity up to stage <span className="text-[#4EABBC] font-black">{maxLevelReached + 1}</span>, showing significant strength in <span className="text-[#E9604F] font-black">{profile.concept >= 4 ? 'Conceptual Depth' : 'Linguistic Resilience'}</span>."
               </p>
               <div className="grid grid-cols-2 gap-4 text-left pt-4">
                  <div className="p-3 bg-white rounded-xl shadow-sm border border-gray-100">
                     <div className="text-[10px] text-gray-400 font-bold uppercase">Max Lexile</div>
                     <div className="text-xl font-bold text-[#111827]">{profile.lex}</div>
                  </div>
                  <div className="p-3 bg-white rounded-xl shadow-sm border border-gray-100">
                     <div className="text-[10px] text-gray-400 font-bold uppercase">Max Syntax</div>
                     <div className="text-xl font-bold text-[#111827]">{profile.syntax}</div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      </div>

      <div className="ucc-card p-12 flex flex-col items-center text-center space-y-4 shadow-xl">
        <h2 className="ucc-title text-4xl text-[#111827]">Cognitive Load Mastery</h2>
        <div className="score-big">{Math.max(0, Math.round(brainPower))}</div>
        <p className="text-gray-500 max-w-md">Based on accuracy across the 5-axis complexity profile and sustainment speed.</p>
        <div className="w-full max-w-lg h-4 bg-gray-50 rounded-full overflow-hidden border border-gray-200">
          <div 
            className="h-full bg-gradient-to-r from-[#4EABBC] to-[#E9604F] transition-all duration-1000"
            style={{ width: `${Math.min(100, Math.max(0, brainPower))}%` }}
          ></div>
        </div>
      </div>
    </div>
  );
};
