
import React from 'react';
import { BrainPillars, Difficulty, GradeLevel, ReadingSkill } from '../types';

interface BrainAnalyticsProps {
  pillars: BrainPillars;
  brainPower: number;
  maxDifficultyReached: Difficulty;
  sessionFinished: boolean;
}

export const BrainAnalytics: React.FC<BrainAnalyticsProps> = ({ pillars, brainPower, maxDifficultyReached, sessionFinished }) => {
  const getGrade = (d: Difficulty): GradeLevel => (d + 2) as GradeLevel;

  const errorBySkill = pillars.itemLog.reduce((acc, item) => {
    if (!item.isCorrect) {
      acc[item.skill] = (acc[item.skill] || 0) + 1;
    }
    return acc;
  }, {} as Record<ReadingSkill, number>);

  const handleExport = () => {
    const date = new Date().toLocaleString();
    const appName = "STAR Reading × Informational: Key Ideas & Details";
    
    let telemetryContent = pillars.itemLog.map((item, index) => `
=== ITEM ${index + 1} ===
Item ID: ${item.id}
Grade: ${item.grade}
Passage: ${item.passage}
Question: ${item.question}
Options: ${item.options.join(", ")}
Skill Tested: ${item.skill}
Error Type: ${item.errorType}
Correct Index: ${item.correctIndex}
Selected Index: ${item.selectedIndex}
Is Correct: ${item.isCorrect}
Time (ms): ${item.timeMs}
Difficulty Before: ${item.difficultyBefore}
Difficulty After: ${item.difficultyAfter}
Timestamp: ${item.timestamp}
`).join("\n");

    const text = `
${appName} - TELEMETRY LOG
--------------------------------------
Date: ${date}

${telemetryContent}

=== SESSION SUMMARY ===
Max Grade Reached: ${getGrade(maxDifficultyReached)}
Accuracy: ${Math.round((pillars.totalAnswers / (pillars.attempts || 1)) * 100)}%
Brain Power: ${Math.round(brainPower)}

ERRORS BY MEANING SKILL:
${Object.entries(errorBySkill).map(([k, v]) => `- ${k}: ${v}`).join('\n') || "None"}

--------------------------------------
Generated by UnCommon Core Logic Systems
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `aria_star_key_ideas_details.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      <div className="ucc-card p-10 border-2 border-[#4EABBC]/30 shadow-2xl relative overflow-hidden">
        <div className="flex justify-between items-center mb-10">
          <h2 className="ucc-title text-4xl text-[#111827]">📊 Meaning Metrics</h2>
          {sessionFinished && (
            <button onClick={handleExport} className="px-6 py-2.5 bg-[#4EABBC] text-white font-black uppercase text-[10px] rounded-xl">
              Export Telemetry (.txt)
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 gap-8">
          <div>
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Errors by Meaning Skill</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
              {["Main Idea", "Supporting Details", "Inference", "Fact vs Opinion"].map(skill => {
                const count = errorBySkill[skill as ReadingSkill] || 0;
                return (
                  <div key={skill} className="flex flex-col justify-between p-4 bg-gray-50 rounded-xl border border-gray-100">
                    <span className="font-bold text-gray-700 text-sm mb-2">{skill}</span>
                    <span className={`self-end px-3 py-1 rounded-full text-xs font-black ${count > 0 ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'}`}>
                      {count} Errors
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      <div className="ucc-card p-12 flex flex-col items-center text-center space-y-4 shadow-xl">
        <h2 className="ucc-title text-4xl">Evidence Tracking Mastery</h2>
        <div className="score-big">{Math.max(0, Math.round(brainPower))}</div>
        <p className="text-gray-500 max-w-md">Based on accuracy, passage complexity, and evidence extraction speed.</p>
        <div className="w-full max-w-lg h-4 bg-gray-50 rounded-full overflow-hidden border">
          <div 
            className="h-full bg-gradient-to-r from-[#4EABBC] to-[#E9604F] transition-all duration-1000"
            style={{ width: `${Math.min(100, Math.max(0, brainPower))}%` }}
          ></div>
        </div>
      </div>
    </div>
  );
};
