
import React, { useState } from 'react';
import { BrainPillars, Difficulty, GradeLevel } from '../types';
import { generateTextWithConfig, getActiveModelConfig } from '../aiSettings';

interface BrainAnalyticsProps {
  pillars: BrainPillars;
  brainPower: number;
  maxDifficultyReached: Difficulty;
  sessionFinished: boolean;
}

export const BrainAnalytics: React.FC<BrainAnalyticsProps> = ({ pillars, brainPower, maxDifficultyReached, sessionFinished }) => {
  const [memo, setMemo] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copyStatus, setCopyStatus] = useState('');

  const getGrade = (d: Difficulty): GradeLevel => (d + 2) as GradeLevel;

  const handleExport = () => {
    const date = new Date().toISOString().split('T')[0];
    const studentName = pillars.metadata?.studentName || "Student";
    const appName = "UCC x Renaissance STAR 360: Base-10 & Place-Value";
    const domain = "Base-10 & Place-Value";
    
    let telemetryContent = "";
    
    pillars.itemLog.forEach((item, index) => {
      const tableDataStr = item.tableData.map(row => `${row.label}: ${row.displayValue} (${row.value})`).join(", ");
      const visualCounts = item.tableData.map(row => `${row.label}: ${row.value}`).join(", ");
      
      telemetryContent += `
=== ITEM ${index + 1} ===
App Name: ${appName}
Domain: ${domain}
Schema: ${item.schema}
Hidden Grade Level: ${item.grade}
Table Data: ${tableDataStr}
Visual Evidence Counts: ${visualCounts}
Question: ${item.question}
Student Answer: ${item.userInput}
Correct Answer: ${item.correctAnswer}
Frame Selected: ${item.operation}
Was Correct: ${item.isCorrect}
Time to Answer (ms): ${item.timeTakenMs}
Hints Used: ${item.hintsUsed}
Difficulty Before: ${item.difficultyBefore}
Difficulty After: ${item.difficultyAfter}
Timestamp: ${item.timestamp}
`;
    });

    const accuracy = Math.round((pillars.totalAnswers / (pillars.attempts || 1)) * 100);
    const avgTime = pillars.levelHistory.length > 0 
      ? (pillars.levelHistory.reduce((acc, curr) => acc + curr.time, 0) / pillars.levelHistory.length).toFixed(1)
      : "0";
    const schemasEncountered = Array.from(new Set(pillars.itemLog.map(i => i.schema))).join(", ");

    const text = `
${appName} - FULL LEARNING TELEMETRY LOG
--------------------------------------
Date: ${new Date().toLocaleString()}
Student Name: ${pillars.metadata?.studentName}
Reported Grade: ${pillars.metadata?.reportedGrade}
Session Duration (s): ${pillars.metadata?.sessionTimerSeconds}
Session Elapsed (ms): ${pillars.metadata?.sessionElapsedMs}
Session Timeout Reached: ${pillars.metadata?.sessionTimeoutReached}
Session Outcome: ${sessionFinished ? 'SUCCESSFUL COMPLETION' : 'INCOMPLETE'}

${telemetryContent}

=== SESSION SUMMARY ===
App Name: ${appName}
Max Difficulty Reached: ${maxDifficultyReached} (Grade ${getGrade(maxDifficultyReached)})
Accuracy: ${accuracy}%
Average Time (s): ${avgTime}
Performance Index Score: ${Math.round(brainPower)}
Schemas Encountered: ${schemasEncountered}
Total Problems: ${pillars.totalAnswers}
Total Attempts: ${pillars.attempts}
Frame Consistency: ${Math.round((pillars.frameCorrectness / (pillars.totalAnswers || 1)) * 100)}%

--------------------------------------
Generated by UnCommon Core Logic Systems
Telemetry Optimized for Educational Reconstruction
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${studentName.replace(/\s+/g, '')}_Math-Base10_${date}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const generateCoachMemo = async () => {
    setIsGenerating(true);
    
    const successItem = pillars.itemLog.find(i => i.isCorrect);
    const failItem = pillars.itemLog.find(i => !i.isCorrect);
    
    const prompt = `Generate a Coach Memo for ${pillars.metadata?.studentName} based STRICTLY on their session telemetry.
    
    Telemetry Summary:
    - Success Example: Schema "${successItem?.schema}", numbers used: [${successItem?.tableData.map(d => `${d.label}: ${d.displayValue}`).join(', ')}], frame: ${successItem?.operation}.
    - Struggle Example: Schema "${failItem?.schema}", Question: "${failItem?.question}", User said: "${failItem?.userInput}", Correct: "${failItem?.correctAnswer}", frame: ${failItem?.operation}.
    - All Schemas Seen: ${Array.from(new Set(pillars.itemLog.map(i => i.schema))).join(', ')}.
    
    Strict Structure Requirements (PSL Insight Loop):
    1. Disarm anxiety: Calm opening.
    2. Name the contrast: Explicitly contrast the specific error (e.g., "${failItem?.userInput}") with the specific success.
    3. Guess-first prompt: Ask the student to hypothesize why the error occurred.
    4. "Yes, and...": Affirm their intuition and bridge to the logic.
    5. Visual intuition: Explain using specific physical analogies like blocks, column shifts, or place-value stacks based on the numbers they faced.
    6. Explain-it-back: Ask them to articulate the pattern.
    7. Teach-someone-else mission: Assign a specific teaching task involving these numbers.
    
    Constraints:
    - Max 200 words.
    - No scores, no grades, no AI mentions, no generic filler ("tricky", "sometimes").
    - Every claim must be traceable to the telemetry provided above.`;

    try {
      const activeConfig = await getActiveModelConfig();
      if (!activeConfig) {
        setMemo('Save a validated provider key and model in Local AI Settings to generate the coach memo.');
        return;
      }

      const response = await generateTextWithConfig(activeConfig, {
        prompt,
        maxOutputTokens: 500,
      });
      setMemo(response || 'Unable to generate memo at this time.');
    } catch (e) {
      setMemo('Error generating memo. Please check connectivity.');
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = () => {
    if (!memo) return;
    navigator.clipboard.writeText(memo);
    setCopyStatus('Copied!');
    setTimeout(() => setCopyStatus(''), 2000);
  };

  const exportMemo = () => {
    if (!memo) return;
    const date = new Date().toISOString().split('T')[0];
    const studentName = pillars.metadata?.studentName || "Student";
    const text = `
UCC x Renaissance STAR 360
Domain: Base-10 & Place-Value
Student: ${studentName}
Date: ${date}

COACH MEMO
${memo}
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${studentName.replace(/\s+/g, '')}_CoachMemo_${date}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      {sessionFinished ? (
        <div className="ucc-card p-10 border-2 border-[#4EABBC]/30 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-[#4EABBC]/5 rounded-full -mr-32 -mt-32 blur-3xl pointer-events-none"></div>
          
          <div className="flex justify-between items-center mb-10">
            <h2 className="ucc-title text-4xl text-[#111827] tracking-tight">🏆 Session Summary</h2>
            <div className="flex gap-4">
              <button 
                onClick={generateCoachMemo}
                disabled={isGenerating}
                className="px-6 py-2.5 bg-[#4EABBC] text-white font-black uppercase tracking-widest text-[10px] rounded-xl hover:bg-[#3d8c9a] transition-all shadow-sm disabled:opacity-50"
              >
                {isGenerating ? 'Generating...' : 'Generate Coach Memo'}
              </button>
              <button 
                onClick={handleExport}
                className="px-6 py-2.5 bg-white border-2 border-[#4EABBC] text-[#4EABBC] font-black uppercase tracking-widest text-[10px] rounded-xl hover:bg-[#4EABBC] hover:text-white transition-all shadow-sm"
              >
                Export Session (.txt)
              </button>
            </div>
          </div>

          {memo && (
            <div className="mb-10 p-8 bg-[#FFFFD5] border-2 border-[#111827]/10 rounded-2xl shadow-inner relative animate-fade-in">
              <div className="flex justify-between items-center mb-4">
                <h3 className="ucc-title text-xl text-[#111827]">Coach Memo</h3>
                <div className="flex gap-3 items-center">
                  <button 
                    onClick={copyToClipboard} 
                    className="text-[10px] font-black uppercase tracking-widest text-[#4EABBC] hover:underline flex items-center gap-1"
                  >
                    {copyStatus || 'Copy Memo'}
                  </button>
                  <div className="w-1 h-1 bg-gray-300 rounded-full"></div>
                  <button 
                    onClick={exportMemo} 
                    className="text-[10px] font-black uppercase tracking-widest text-[#E9604F] hover:underline"
                  >
                    Export Memo (.txt)
                  </button>
                </div>
              </div>
              <p className="text-gray-700 font-medium leading-relaxed whitespace-pre-wrap">{memo}</p>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-3 md:grid-cols-5 gap-5">
            {[1, 2, 3, 4, 5].map((d) => {
              const difficulty = d as Difficulty;
              const reached = maxDifficultyReached >= difficulty;
              const grade = getGrade(difficulty);
              return (
                <div key={d} className={`p-6 rounded-3xl text-center border-2 transition-all group ${reached ? 'border-[#4EABBC] bg-[#4EABBC]/5 shadow-lg' : 'border-gray-100 opacity-40 grayscale'}`}>
                  <p className="text-[10px] uppercase font-black text-gray-400 tracking-widest mb-2 group-hover:text-[#4EABBC] transition-colors">Level {d}</p>
                  <p className="ucc-title text-xl text-[#111827]">
                    Grade {grade}{grade === 7 ? ' 🚀' : ''}
                  </p>
                  <div className="mt-4 flex justify-center">
                    <span className={`w-10 h-10 rounded-full flex items-center justify-center text-xl shadow-sm border ${reached ? 'bg-white border-[#4EABBC]/20 text-[#4EABBC]' : 'bg-gray-50 border-gray-100 text-gray-300'}`}>
                      {reached ? '✓' : '🔒'}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
          <p className="text-center text-gray-500 mt-10 italic font-medium max-w-lg mx-auto leading-relaxed">
            “Your brain climbed through Base-10 reasoning as place value, regrouping, decimals, and power scaling. Each level you reach makes the structure of numbers easier to decode.”
          </p>
        </div>
      ) : (
        <div className="ucc-card p-20 flex flex-col items-center justify-center text-center space-y-4 border-2 border-dashed border-gray-200">
          <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center text-2xl">🔒</div>
          <h2 className="ucc-title text-2xl text-gray-400">Testing in Progress</h2>
          <p className="text-gray-400 max-w-sm">Complete your test session to unlock the cognitive pillars and see your Place-Value Power evaluation.</p>
        </div>
      )}

      {sessionFinished && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="ucc-card p-8 border-l-[6px] border-[#4EABBC] flex flex-col">
              <h4 className="ucc-title text-[#4EABBC] text-lg mb-1 tracking-wide">Cognitive Ladder</h4>
              <p className="text-[11px] text-gray-500 font-medium leading-tight mb-3">“How much Base-10 you can actually use.”</p>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-4">Grade {getGrade(maxDifficultyReached)} Reached</p>
              <div className="space-y-3 mt-auto">
                <p className="text-[10px] text-[#4EABBC] font-black uppercase tracking-widest leading-relaxed">“Each level you reach means your brain can handle more complex number structures.”</p>
              </div>
            </div>

            <div className="ucc-card p-8 border-l-[6px] border-[#E9604F] flex flex-col">
              <h4 className="ucc-title text-[#E9604F] text-lg mb-1 tracking-wide">Frame Precision</h4>
              <p className="text-[11px] text-gray-500 font-medium leading-tight mb-3">“Did you use the right kind of thinking?”</p>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-4">Precision Score: {pillars.totalAnswers > 0 ? Math.round((pillars.frameCorrectness / pillars.totalAnswers) * 100) : 0}%</p>
              <div className="flex flex-col pt-2 mt-auto">
                <p className="text-[10px] text-[#E9604F] font-black uppercase tracking-widest leading-relaxed">“Some problems need regrouping. Some need decimals. Some need power scaling.”</p>
              </div>
            </div>

            <div className="ucc-card p-8 border-l-[6px] border-[#8b5cf6] flex flex-col">
              <h4 className="ucc-title text-[#8b5cf6] text-lg mb-1 tracking-wide">Strategic Support</h4>
              <p className="text-[11px] text-gray-500 font-medium leading-tight mb-3">“How much help you needed.”</p>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-4">{pillars.hintsUsed} Hints Used</p>
              <div className="space-y-3 mt-auto">
                <p className="text-[10px] text-[#8b5cf6] font-black uppercase tracking-widest leading-relaxed">“Fewer hints means your brain did the work.”</p>
              </div>
            </div>

            <div className="ucc-card p-8 border-l-[6px] border-rose-500 flex flex-col">
              <h4 className="ucc-title text-rose-500 text-lg mb-1 tracking-wide">Velocity</h4>
              <p className="text-[11px] text-gray-500 font-medium leading-tight mb-3">“How fast you think when the clock is on.”</p>
              <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-4">Speed Metrics</p>
              <div className="space-y-2 mt-auto">
                <p className="text-[10px] text-rose-500 font-black uppercase tracking-widest leading-relaxed">“Number sense decisions aren’t slow.”</p>
              </div>
            </div>
          </div>

          <div className="ucc-card p-12 flex flex-col items-center justify-center text-center space-y-4 bg-white border border-gray-100 shadow-xl relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-[#4EABBC]/5 via-transparent to-[#E9604F]/5 pointer-events-none"></div>
            <h2 className="ucc-title text-4xl text-[#111827] mb-0">Coach Performance Index</h2>
            <div className="score-big drop-shadow-sm select-none">
              {Math.max(0, Math.round(brainPower))}
            </div>
            <p className="text-[13px] text-[#4EABBC] font-black uppercase tracking-[0.15em] mb-2">“How strong your brain performed today.”</p>
            <p className="text-gray-500 max-w-md font-medium leading-relaxed">
              “This blends how high you climbed, how cleanly you solved, how much help you used, and how fast you thought.”
            </p>
            <div className="w-full max-w-lg h-4 bg-gray-50 rounded-full border border-gray-100 p-0.5 relative">
              <div 
                className="h-full bg-gradient-to-r from-[#4EABBC] via-[#4EABBC] to-[#E9604F] rounded-full transition-all duration-[2000ms] shadow-[0_0_15px_rgba(78,171,188,0.3)]"
                style={{ width: `${Math.min(100, Math.max(0, brainPower))}%` }}
              ></div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
