
import React from 'react';
import { BrainPillars, Difficulty, GradeLevel, LiteratureLens, DistractorLogic } from '../types';

interface BrainAnalyticsProps {
  pillars: BrainPillars;
  brainPower: number;
  maxDifficultyReached: Difficulty;
  sessionFinished: boolean;
}

export const BrainAnalytics: React.FC<BrainAnalyticsProps> = ({ pillars, brainPower, maxDifficultyReached, sessionFinished }) => {
  const getGrade = (d: Difficulty): GradeLevel => (d + 2) as GradeLevel;

  const errorByLens = pillars.itemLog.reduce((acc, item) => {
    if (!item.isCorrect) {
      acc[item.lens] = (acc[item.lens] || 0) + 1;
    }
    return acc;
  }, {} as Record<LiteratureLens, number>);

  const errorByDistractor = pillars.itemLog.reduce((acc, item) => {
    if (!item.isCorrect) {
      acc[item.distractorLogic] = (acc[item.distractorLogic] || 0) + 1;
    }
    return acc;
  }, {} as Record<DistractorLogic, number>);

  const handleExport = () => {
    const date = new Date().toLocaleString();
    const appName = "STAR Reading × Literature: Craft & Structure";
    
    let telemetryContent = pillars.itemLog.map((item, index) => `
=== ITEM ${index + 1} ===
Item ID: ${item.id}
Grade Meta: ${item.gradeMeta}
Difficulty: ${item.difficulty}
Lens: ${item.lens}
Distractor Logic: ${item.distractorLogic}
Correct Index: ${item.correctIndex}
Chosen Index: ${item.chosenIndex}
Is Correct: ${item.isCorrect}
Time (ms): ${item.timeMs}
Difficulty Before: ${item.difficultyBefore}
Difficulty After: ${item.difficultyAfter}
Passage: ${item.passage}
Question: ${item.question}
Timestamp: ${item.timestamp}
`).join("\n");

    const text = `
${appName} - TELEMETRY LOG
--------------------------------------
Date: ${date}

${telemetryContent}

=== SESSION SUMMARY ===
Max Difficulty Reached: ${maxDifficultyReached} (Grade ${getGrade(maxDifficultyReached)})
Accuracy: ${Math.round((pillars.totalAnswers / (pillars.attempts || 1)) * 100)}%
Craft & Structure Mastery: ${Math.round(brainPower)}

ERRORS BY LENS:
${Object.entries(errorByLens).map(([k, v]) => `- ${k}: ${v}`).join('\n') || "None"}

ERRORS BY DISTRACTOR LOGIC:
${Object.entries(errorByDistractor).map(([k, v]) => `- ${k}: ${v}`).join('\n') || "None"}

--------------------------------------
Generated by UnCommon Core Logic Systems
`.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `aria_star_literature_craft_structure.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      <div className="ucc-card p-10 border-2 border-[#4EABBC]/30 shadow-2xl relative overflow-hidden">
        <div className="flex justify-between items-center mb-10">
          <h2 className="ucc-title text-4xl text-[#111827]">📊 Literature Metrics</h2>
          {sessionFinished && (
            <button onClick={handleExport} className="px-6 py-2.5 bg-[#4EABBC] text-white font-black uppercase text-[10px] rounded-xl">
              Export Telemetry (.txt)
            </button>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Errors by Literature Lens</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {["NARRATOR", "TONE", "FIGURATIVE", "STRUCTURE", "AUTHOR_INTENT"].map(lens => {
                const count = errorByLens[lens as LiteratureLens] || 0;
                return (
                  <div key={lens} className="flex flex-col justify-between p-4 bg-gray-50 rounded-xl border border-gray-100">
                    <span className="font-bold text-gray-700 text-sm mb-2 capitalize">{lens.replace('_', ' ')}</span>
                    <span className={`self-end px-3 py-1 rounded-full text-xs font-black ${count > 0 ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'}`}>
                      {count} Errors
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          <div>
            <h3 className="text-xs font-black uppercase tracking-widest text-gray-400 mb-4">Errors by Distractor Logic</h3>
            <div className="space-y-2">
              {Object.entries(errorByDistractor).map(([k, v]) => (
                <div key={k} className="flex justify-between items-center p-3 bg-gray-50 rounded-lg">
                  <span className="capitalize font-bold text-gray-700 text-sm">{k.replace('_', ' ')}</span>
                  <span className="bg-red-100 text-red-600 px-3 py-1 rounded-full text-xs font-black">{v}</span>
                </div>
              ))}
              {Object.entries(errorByDistractor).length === 0 && (
                <p className="text-gray-400 italic text-sm">No logical errors recorded.</p>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="ucc-card p-12 flex flex-col items-center text-center space-y-4 shadow-xl">
        <h2 className="ucc-title text-4xl">Literature Mastery</h2>
        <div className="score-big">{Math.max(0, Math.round(brainPower))}</div>
        <p className="text-gray-500 max-w-md">Based on accuracy, passage complexity, and structural analysis speed.</p>
        <div className="w-full max-w-lg h-4 bg-gray-50 rounded-full overflow-hidden border">
          <div 
            className="h-full bg-gradient-to-r from-[#4EABBC] to-[#E9604F] transition-all duration-1000"
            style={{ width: `${Math.min(100, Math.max(0, brainPower))}%` }}
          ></div>
        </div>
      </div>
    </div>
  );
};
